#### general settings
name: BLINDnew_FT_DUF_16L_R_S2_fin
use_tb_logger: true
model: video_base
distortion: sr
scale: 2
gpu_ids: [1] # [0,1,2,3,4,5,6,7]

#### datasets
datasets:
  train:
    name: REDS
    mode: REDS
    interval_list: [1]
    random_reverse: false
    border_mode: false
    data_root: '../dataset'
    img_type: bin

    N_frames: 7
    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 16
    patch_size: 64
    use_flip: true
    use_rot: true
    kernel_size: 21
    color: RGB
  val:
    name: REDS #Vid4+
    mode: video_test
    dataroot_GT: ../dataset/REDS/train/HR # ../dataset/Vid4/HR+
    dataroot_LQ: ../dataset/REDS/train/LR_bicubic #../dataset/Vid4/LR_bicubic+
    cache_data: True
    N_frames: 7
    padding: new_info
    degradation_mode: preset

#### network structures
network_G:
  which_model_G: DUF
  layers: 16

network_E:
  which_model_E: ~
#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/DUF_16L_REDS_S2.pth
  strict_load: true
  resume_state: ../experiments/BLINDnew_FT_DUF_16L_R_S2_fin/training_state/10000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 5e-5 # 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  epochs: 1000
  niter: 100000
  warmup_iter: -1  # -1: no warm up
  lr_steps: [50000, 75000]
  lr_gamma: 0.2

  pixel_criterion: huber
  pixel_weight: 1.0
  val_freq: !!float 2500 # 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2500 #5e3
