#### general settings
name: BLINDnew_FT_EDVR_M_V_S2_fin_Eng
use_tb_logger: true
model: video_base
distortion: sr
scale: 2
gpu_ids: [1] # [0,1,2,3,4,5,6,7]

#### datasets
datasets:
  train:
    name: Vimeo
    mode: Vimeo
    interval_list: [1]
    random_reverse: false
    border_mode: false
    data_root: '../dataset'
    img_type: img

    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 16
    patch_size: 64
    use_flip: true
    use_rot: true
    kernel_size: 21
    color: RGB
  val:
    name: Vid4 #+REDS
    mode: video_test
    dataroot_GT: ../dataset/Vid4/HR #+../dataset/REDS/train/HR
    dataroot_LQ: ../dataset/Vid4/LR_bicubic #+../dataset/REDS/train/LR_bicubic
    cache_data: True
    N_frames: 5
    padding: new_info
    degradation_mode: preset

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: true

network_E:
  which_model_E: ~
#### path
path:
  pretrain_model_G: ../experiments/BLINDnew_FT_EDVR_M_V_S2_fin/models/7500_G.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-6 # 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  epochs: 1000
  niter: 100000
  warmup_iter: -1  # -1: no warm up
  lr_steps: [50000, 75000]
  lr_gamma: 0.2

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1000 # 2500 # 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100 # 200
  save_checkpoint_freq: !!float 1000 #2500 #5e3
